name: Check
on:
  pull_request:
  workflow_dispatch:
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tsconfig: [node-22, node-ts, pedantic]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
      - name: Install dependencies
        run: npm ci
      - name: Create source file
        run: touch index.ts
      - name: Compile
        run: npm exec -- tsc --project tsconfig.${{ matrix.tsconfig }}.json
