name: Check
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tsconfig: [node-22, node-ts, pedantic]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Create source file
        run: touch index.ts
      - name: Compile
        run: pnpm exec -- tsc --project tsconfig.${{ matrix.tsconfig }}.json
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Check format
        run: pnpm run format:check
