name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: The Git tag to checkout.
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ inputs.tag || github.ref }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ">=24.5" # contains npm>=11.5.1
      - name: Install dependencies
        run: pnpm install
      - name: Set version
        run: pnpm version from-git --no-git-tag-version
      - name: Publish
        run: pnpm publish --no-git-checks
