name: Release
on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}
jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yaml

  release:
    name: Release
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: pnpm exec -- semantic-release
